---
server:
  address: localhost
  port: 8020
  servlet:
    context-path: /auth
  compression:
    enabled: true
  http2:
    enabled: true
  error:
    whitelabel:
      enabled: false

#http://localhost:8020/auth/swagger-ui/
springfox:
  documentation:
    swagger-ui:
      enabled: true

spring:
  profiles:
    ############
    active: dev
    ############
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/auth_db
    user: ${DB_USER}
    password: ${DB_PASSWORD}
    fail-on-missing-locations: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    out-of-order: true

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    generate-ddl: true
    show-sql: false
    open-in-view: false
    hibernate:
      ############
      ddl-auto: none
      ############
    properties:
      hibernate:
        generate_statistics: true
        current_session_context_class: "thread"
        default_batch_fetch_size: 20
        format_sql: true
        connection:
          autocommit: false
        jdbc:
          batch_size: 10
          order_inserts: true
          order_updates: true

  jackson:
      serialization:
        indent-output: true
        write_dates_as_timestamps: false
  mvc:
    throw-exception-if-no-handler-found: true

logging:
  config: classpath:log4j2.properties

# TODO: вынести в параметры
jwt:
  secret-key: "authsecret-lsdfahksdjfhkljsdfkjsdhfaslkjdhfkajlsdfha-skldjhfa-sldkfhaslcxkvh-dgfasdkfjhkjh"
  access-expires-at: 3600000
  refresh-expires-at: 8640000

sign-in:
  tries: 10
  expire: 3600000

---
#DEV
spring:
  config:
    activate:
      on-profile: dev

logging:
  level:
    ROOT: INFO
    org:
      springframework:
        web: DEBUG
        data:
          jdbc: DEBUG
        transaction: DEBUG
        orm.jpa: DEBUG
---
#PROD
spring:
  config:
    activate:
      on-profile: prod

logging:
  level:
    ROOT: ERROR
    org:
      springframework:
        web: INFO
        data:
          jdbc: INFO
