---
server:
  address: localhost
  port: 8030
  servlet:
    context-path: /animals
  compression:
    enabled: true
  http2:
    enabled: true
  error:
    whitelabel:
      enabled: false

#http://localhost:8030/auth/swagger-ui/
springfox:
  documentation:
    swagger-ui:
      enabled: true

spring:
  profiles:
    ############
    active: dev
    ############
  datasource:
    url: jdbc:postgresql://localhost:5432/animals_db
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: false
    url: jdbc:postgresql://localhost:5432/animals_db
    user: ${DB_USER}
    password: ${DB_PASSWORD}
    fail-on-missing-locations: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    out-of-order: false

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    generate-ddl: false
    show-sql: true
    open-in-view: false
    hibernate:
      ############
      ddl-auto: none
      ############
    properties:
      hibernate:
        default_schema: "public"
#        generate_statistics: true
        current_session_context_class: thread
        default_batch_fetch_size: 5
        format_sql: true
        globally_quoted_identifiers: true
        connection:
          autocommit: false
        jdbc:
          batch_size: 10
          order_inserts: true
          order_updates: true
          batch_versioned_data: true
#        id:
#          new_generator_mappings: false

  jackson:
    serialization:
      indent-output: true
      write_dates_as_timestamps: false
  mvc:
    throw-exception-if-no-handler-found: true
  mustache:
    check-template-location: false

logging:
  config: classpath:log4j2.properties

auth:
  api:
    base-verify-token-url: http://localhost:8020
verify-token-url: ${auth.api.base-verify-token-url}/auth/api/v1/verify/token
#verify-token-url: http://localhost:8020/auth/api/v1/verify/token
---
#DEV
spring:
  config:
    activate:
      on-profile: dev

logging:
  level:
    ROOT: INFO
    org:
      springframework:
        web: DEBUG
        data:
          jdbc: DEBUG
        transaction: DEBUG
        orm.jpa: DEBUG
---
#PROD
spring:
  config:
    activate:
      on-profile: prod

logging:
  level:
    ROOT: ERROR
    org:
      springframework:
        web: INFO
        data:
          jdbc: INFO
