server:
  address: localhost
  port: 8030
  servlet:
    context-path: /animals
  compression:
    enabled: true
  http2:
    enabled: true
  error:
    whitelabel:
      enabled: false

springfox:
  documentation:
    swagger-ui:
      enabled: true

spring:
  profiles:
    active: dev
  mvc:
    throw-exception-if-no-handler-found: true

---
#DEV
spring:
  config:
    activate:
      on-profile: dev

####
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:animals_db;MODE=PostgreSQL
#    username: root
#    password: 123
#  sql:
#    init:
#      mode: always
#      platform: h2
#  h2:
#    console:
#     enabled: true
#     path: /h2-console
#  flyway:
#    enabled: false

####
  datasource:
    url: jdbc:postgresql://localhost:5432/animals_db
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/animals_db
    user: ${DB_USER}
    password: ${DB_PASSWORD}
    fail-on-missing-locations: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    out-of-order: true
  ####

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    generate-ddl: true
    show-sql: true
    # решает ошибку ClassCastException EntityManagerHolder
    open-in-view: false
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: true

    properties:
      hibernate:
        generate_statistics: true
        current_session_context_class: "thread"
        default_batch_fetch_size: 20
        format_sql: true
        connection:
          autocommit: false
        jdbc:
          batch_size: 10
          order_inserts: true
          order_updates: true

  jackson:
    serialization:
      indent-output: true
      write_dates_as_timestamps: false

logging:
  config: classpath:log4j2.properties
  level:
    ROOT: INFO
    org:
      springframework:
        web: DEBUG
        data:
          jdbc: DEBUG
        transaction: DEBUG
        orm.jpa: DEBUG

---
#PROD
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://localhost:5432/animals_db
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: false
    url: jdbc:postgresql://localhost:5432/animals_db
    user: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    generate-ddl: true
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: true

    properties:
      hibernate:
        generate_statistics: true
        current_session_context_class: "thread"
        default_batch_fetch_size: 20
        format_sql: true
        connection:
          autocommit: false
        jdbc:
          batch_size: 10
          order_inserts: true
          order_updates: true

  jackson:
    serialization:
      indent-output: true
      write_dates_as_timestamps: false

logging:
  config: classpath:log4j2.properties
  level:
    ROOT: ERROR
    org:
      springframework:
        web: INFO
        data:
          jdbc: INFO
